Repository threefoldtech/js-sdk, pull requests merged in 2021-01, with the labels that each got.

#2115 update js-ng to 11.0b11...
  poetry.lock
  pyproject.toml
Labels: priority_critical

#2232 Add missing fields in the stellar client
  jumpscale/clients/stellar/stellar.py
Labels: priority_major

#2077 Add ETCD Chart
  jumpscale/packages/vdc_dashboard/chats/etcd.py
  jumpscale/packages/vdc_dashboard/frontend/assets/etcd.png
  jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Solution.vue
  jumpscale/packages/vdc_dashboard/frontend/data.js
  jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py
Labels: type_feature
