Repository threefoldtech/js-sdk, pull requests merged in 2021-03, with the labels that each got.

#2617 add 4to6 gw test
  docs/tests/sals/automated_chatflows/test_solutions.md
  solutions_automation/dashboard_solutions/four_to6gw.py
  solutions_automation/deployer.py
  tests/sals/automated_chatflows/test_solutions.py
Labels: type_feature

#2707 Development vdc storage farms selection
  jumpscale/packages/vdc/chats/new_vdc.py
  jumpscale/sals/vdc/deployer.py
  jumpscale/sals/vdc/scheduler.py
  jumpscale/sals/vdc/threebot.py
  solutions_automation/vdc/dashboard/vdc.py
  solutions_automation/vdc/deployer.py
Labels: type_feature, type_story

#2706 init backup & restore table
  jumpscale/packages/vdc_dashboard/bottle/backup.py
  jumpscale/packages/vdc_dashboard/frontend/api.js
  jumpscale/packages/vdc_dashboard/frontend/components/base/Dialog.vue
  jumpscale/packages/vdc_dashboard/frontend/components/base/JSONRenderer.vue
  jumpscale/packages/vdc_dashboard/frontend/components/base/Popup.vue
  jumpscale/packages/vdc_dashboard/frontend/components/marketplace/Delete.vue
  jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Actions.vue
  jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue
  jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Delete.vue
  jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Home.vue
  jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Restore.vue
  jumpscale/packages/vdc_dashboard/frontend/index.html
  jumpscale/packages/vdc_dashboard/frontend/index.js
Labels: type_feature

#2850 VDC Billing Docs
  docs/vdc/billing.md
  docs/vdc/vdc_deployer.md
Labels: type_documentation
